### ISSUE TITLE
Login after install

### ISSUE THREAD

**Issue by povode** [juriansluiman/groceri.es#1]
Is it just me or you don't mention how to create a login after deployment of docker container?

Any advice would be welcome.

Regards,
Petyo

**Comment by navanod-git** [comment]
Would also like to know this too, really keen to try out this project. Spent far too long trying to work out a username  password combination.

Looking forward to a response.

**Comment by navanod-git** [comment]
Emailed the Dev directly, response below, haven't had a chance to try the login process (my son was born yesterday, so hands are happily full elsewhere 😀):

Thanks for trying out groceri.es! To be honest, the current online progress isn't that far that there's a fully fledged authentication system. Currently there are some views in progress to provide for a signup page, but those haven't been committed yet. Due to the latest pandemic I haven't had the time to push things through and current state is pretty useless to be honest.

If you load the fixture data (go to http://my-ip-here/generator) and then login with username "jurian", password "password" you can continue browsing menu scheme and recipe listings, but it's still view-only. Afaik you can't add recipes or plan meals on a schedule, that's all on the todo.

You can follow the project on Github (start it afaik) and you'll get the updates. I hope to publish some new stuff in 2-3 weeks hopefully.
